### ISSUE TITLE
Incompatibility between UI and Pipeline-Serivce

### ISSUE THREAD

**Issue by felix-oq** [jvalue/ods#353]
While writing the Consumer-Driven Contract Tests in #352, I encountered an incompatibility between the UI and the Pipeline-Service during their integration. The integration failure occurs when getting pipelines by a datasource id.
&nbsp;
The UI tries to interpret the response as a single Pipeline-Object:
https://github.com/jvalue/ods/blob/57e8070222b4703c76db856619f8605d0ce1409c/ui/src/pipeline/pipelineRest.ts#L26-L29
&nbsp;
The Pipeline-Serivce however sends an array of Pipeline-Objects as response:
https://github.com/jvalue/ods/blob/57e8070222b4703c76db856619f8605d0ce1409c/pipeline/src/api/rest/pipelineConfigEndpoint.ts#L83-L92
https://github.com/jvalue/ods/blob/57e8070222b4703c76db856619f8605d0ce1409c/pipeline/src/pipeline-config/pipelineConfigManager.ts#L36-L39

**Comment by f3l1x98** [comment]
I have been looking into it and that is definitely a UI issue, but:
The UI REST Api function `getPipelineByDatasourceId` is **only used once** for the Vuex action, **BUT**:
This Vuex action `loadPipelineByDatasourceId` is **never used**
https://github.com/jvalue/ods/blob/57e8070222b4703c76db856619f8605d0ce1409c/ui/src/pipeline/pipeline.module.ts#L75-L78

Additionally the logic of the action is wrong because it depends on the REST call returning only one Pipeline, but from my understanding (I am fairly new to the project) a datasource can have multiple pipeline(-config)s.
Thus my question @georg-schwarz : 
Is there any reason to keep this Vuex action, even though it is unused?

**Comment by georg-schwarz** [comment]
Ah I remember, there was a feature planned for it (showing pipelines for a data source). Please keep it!
