### ISSUE TITLE
UI image crashes

### ISSUE THREAD

**Issue by knusperkrone** [jvalue/ods#371]
@georg-schwarz
UI image does no longer boot up.

After executing:
```
docker pull ghcr.io/jvalue/open-data-service/ui:latest
docker run ghcr.io/jvalue/open-data-service/ui:latest
# returns instantly
```

Kubernetes itself shows a `CrashLoopBackOff`.

**Comment by knusperkrone** [comment]
@felix-oq might be related to #368

**Comment by felix-oq** [comment]
The issue is probably caused by the order of steps in the Workflow:
https://github.com/jvalue/ods/blob/fe76ed84d487ff82f6847dabf5efa13f0ce70dad/.github/workflows/ods.yml#L236-L260
The Image is uploaded right after the CDC-Tests are executed. Due to the changes in #368, the script for CDCT builds a different cut-down version of the UI image, that is just capable of executing the CDC-Tests. Thus, reordering the steps in the workflow such that the correct image is uploaded should fix the problem.

I will try to solve the issue and create a PR as soon as I succeed.

**Comment by georg-schwarz** [comment]
Fixed?

**Comment by felix-oq** [comment]
Yes is should be fixed by now because the bug cannot be reproduced anymore. Following the steps above will run the UI as expected.
